version: "3.2"
services:
  server:
    restart: always
    container_name: server
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  client:
    restart: always
    command: npm -i start
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server